import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../Components/Header/Header'
import Hero from '../Components/Hero/Hero'
import Movieset from '../Components/Movieset/Movieset'

export default function Home({data,data2}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Hero />
        <Movieset collection={[data,data2]} />
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {

  let url = "https://www.omdbapi.com/?s=avengers&apikey=3e9c1c84"
  let spiderman = "https://www.omdbapi.com/?s=batman&apikey=3e9c1c84"
 
  const res = await fetch(url)
  const data = await res.json()

  const res2 =  await fetch(spiderman)
  const data2 = await res2.json()

  return {
     props: {
          data:{
            data:data,
            category:"Avengers"
          },
          data2:{
            data:data2,
            category:"Batman"
          }
      },
     }
}
